### ISSUE TITLE
Dataset Release

### ISSUE THREAD

**Issue by AIRobotZhang** [psunlpgroup/CONTaiNER#3]
Could you release the few-shot datasets in Table 3? Because I find these full datasets are all available publicly. What I need is the same few-shot settings with you. Thanks a lot.

**Comment by Sarathismg** [comment]
Hi, Thanks for bringing up this issue. In that case, I can clean those datasets up and pre-process them in the same format as we did in Few-NERD. I can do it next month once I get some free time. I prefer mailing those dataset splits rather than putting them here since I did not author those datasets.

**Comment by AIRobotZhang** [comment]
> Hi, Thanks for bringing up this issue. In that case, I can clean those datasets up and pre-process them in the same format as we did in Few-NERD. I can do it next month once I get some free time. I prefer mailing those dataset splits rather than putting them here since I did not author those datasets.

Thanks for your prompt reply and valuable works.
Best wishes. 
My Email is xing_hua_zhang@126.com

**Comment by W-lw** [comment]
> Hi, Thanks for bringing up this issue. In that case, I can clean those datasets up and pre-process them in the same format as we did in Few-NERD. I can do it next month once I get some free time. I prefer mailing those dataset splits rather than putting them here since I did not author those datasets.

Hello, I would be greatly appreciated if you could also mail those datasets to me, as I am also doing related research on few-shot NER. My email is [w_liwen@bupt.edu.cn](w_liwen@bupt.edu.cn).

**Comment by liyongqi2002** [comment]
Hello, I also need the sampled data in Table 3 for fair comparison. Thank you very much.My email is [liyongqi@whu.edu.cn](url)

**Comment by liyongqi2002** [comment]
> Hi, Thanks for bringing up this issue. In that case, I can clean those datasets up and pre-process them in the same format as we did in Few-NERD. I can do it next month once I get some free time. I prefer mailing those dataset splits rather than putting them here since I did not author those datasets.

Hello, I also need the sampled data in Table 3 for fair comparison. Thank you very much.My email is [liyongqi@whu.edu.cn](https://github.com/psunlpgroup/CONTaiNER/issues/url)

**Comment by yizumi426** [comment]
> Hi, Thanks for bringing up this issue. In that case, I can clean those datasets up and pre-process them in the same format as we did in Few-NERD. I can do it next month once I get some free time. I prefer mailing those dataset splits rather than putting them here since I did not author those datasets.

Hello, I also need the sampled data, thank you very much. My email is **lxl.tju@qq.com**

**Comment by lylylylylyly** [comment]
> 

Hello, I am a PhD student doing research about few-shot NER. I may need the sampled data in Table 3 for a fair comparison. Look forward to your mail. Thanks! My email is 219019034@link.cuhk.edu.cn

**Comment by WeerayutBu** [comment]
Hello, I am a Ph.D. student doing research about NER;  I would need to use the same datasets in Table 3. Please forward it to my mail weerayut.b_s20@vistec.ac.th; Thank you very much.

**Comment by rollben** [comment]
> Hi, Thanks for bringing up this issue. In that case, I can clean those datasets up and pre-process them in the same format as we did in Few-NERD. I can do it next month once I get some free time. I prefer mailing those dataset splits rather than putting them here since I did not author those datasets.

Very appreciated  please also email those datasets to me  ,thanks! . 
My email is junwenzhang@zju.edu.cn

**Comment by rollben** [comment]
> Hi, Thanks for bringing up this issue. In that case, I can clean those datasets up and pre-process them in the same format as we did in Few-NERD. I can do it next month once I get some free time. I prefer mailing those dataset splits rather than putting them here since I did not author those datasets.

Very appreciated  please also email those datasets to me  ,thanks! . 
My email is junwenzhang@zju.edu.cn

**Comment by WeerayutBu** [comment]
> Hi, Thanks for bringing up this issue. In that case, I can clean those datasets up and pre-process them in the same format as we did in Few-NERD. I can do it next month once I get some free time. I prefer mailing those dataset splits rather than putting them here since I did not author those datasets.

Thank you for your effort, I appreciate that; could you please send me the dataset, it will help me a lot in my project. Weerayut.b_s20@vistec.ac.th

**Comment by FalAnge1217** [comment]
> > Hi, Thanks for bringing up this issue. In that case, I can clean those datasets up and pre-process them in the same format as we did in Few-NERD. I can do it next month once I get some free time. I prefer mailing those dataset splits rather than putting them here since I did not author those datasets.
> 
> Hello, I also need the sampled data in Table 3 for fair comparison. Thank you very much.My email is [liyongqi@whu.edu.cn](https://github.com/psunlpgroup/CONTaiNER/issues/url)



> > Hi, Thanks for bringing up this issue. In that case, I can clean those datasets up and pre-process them in the same format as we did in Few-NERD. I can do it next month once I get some free time. I prefer mailing those dataset splits rather than putting them here since I did not author those datasets.
> 
> Hello, I also need the sampled data in Table 3 for fair comparison. Thank you very much.My email is [liyongqi@whu.edu.cn](https://github.com/psunlpgroup/CONTaiNER/issues/url)

你好，能给我分享一下 sampled data吗？我的邮箱是2674053421@qq.com，非常感谢

**Comment by Emma1066** [comment]
> Hi, Thanks for bringing up this issue. In that case, I can clean those datasets up and pre-process them in the same format we did in Few-NERD. I can do it next month once I get some free time. I prefer mailing those dataset splits rather than putting them here since I did not author those datasets.

Thanks for sharing your excellent work. I am a Ph.D. student, and I am also working on Few-shot NER. Could you please email the datasets to me? Thank you so much. My email is 11921049@zju.edu.cn.

**Comment by unveiled-the-red-hat** [comment]
Thank you for your effort. Could you please email the datasets to me? Thank you so much. My email is [220201961@seu.edu.cn](mailto:220201961@seu.edu.cn).

**Comment by linyigang2022** [comment]
I am also conducting research on few-shot NER, and I need the sampled data from Table 3. Thank you very much! Here is my email: linyigang2022@email.szu.edu.cn.

**Comment by linyigang2022** [comment]
> Hi, Thanks for bringing up this issue. In that case, I can clean those datasets up and pre-process them in the same format as we did in Few-NERD. I can do it next month once I get some free time. I prefer mailing those dataset splits rather than putting them here since I did not author those datasets.

Hello. Thanks for sharing your excellent work. I am also doing research about few-shot NER, and I need the sampled data from Table 3. Thank you very much! Here is my email: linyigang2022@email.szu.edu.cn.
