### ISSUE TITLE
数据链接失效

### ISSUE THREAD

**Issue by jiayuemoon** [psunlpgroup/CONTaiNER#5]
I can't get the episode_data.zip through the given link,can you update this?

**Comment by jiayuemoon** [comment]
关于数据链接失效问题，目前通过相关论文的搜索找到了源数据链接，利用下载的数据可以暂时把代码跑起来（但未知是否和作者提供的一致），仅供参考
data/few-nerd/inter（intra）/train.txt：https://ningding97.github.io/fewnerd/
saved_models.zip：https://github.com/thunlp/Few-NERD
在相应的网页中搜索对应的关键词，inter/intra/episode就可以找到源数据的链接/运行代码得到源数据

**Comment by Sarathismg** [comment]
Thank you so much for pointing this out. I am putting that in the description. Looks like you are correct regarding this issue, Few-NERD dataset link has been updated

**Comment by sepidzn** [comment]
The provided link is either expired; does anyone have the correct one?
